<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup><OutputType>Exe</OutputType><TargetFramework>net10.0-windows</TargetFramework><ImplicitUsings>enable</ImplicitUsings><Nullable>enable</Nullable></PropertyGroup>
  <ItemGroup>
    <Reference Include="WzComparerR2.WzLib"><HintPath>../../artifacts/tools/WzComparerR2/bin/Lib/WzComparerR2.WzLib.dll</HintPath></Reference>
    <Reference Include="System.Drawing.Common"><HintPath>../../artifacts/tools/WzComparerR2/bin/Lib/System.Drawing.Common.dll</HintPath></Reference>
  </ItemGroup>
</Project>
